version: 2

models:
  - name: model_fact_campaign_interactions
    description: "Fact model for campaign interactions"
    tags: staging
    columns:
      - name: InteractionID
        description: "Unique ID for the interaction"
        tests:
          - not_null
          - unique
      - name: CampaignID
        description: "Foreign Key referencing the campaign"
        tests:
          - not_null
      - name: OrderID
        description: "ID of the order linked to the interaction"
      - name: CustomerID
        description: "Foreign Key referencing the customer"
        tests:
          - not_null
      - name: InteractionDatetime
        description: "Timestamp of the interaction"
        tests:
          - not_null
      - name: EventType
        description: "Type of interaction event (e.g., click, impression)"
        tests:
          - not_null
      - name: Platform
        description: "Platform where the interaction took place (e.g., Google, Facebook)"
        tests:
          - not_null
      - name: DeviceType
        description: "Type of device used during the interaction (e.g., iOS, Android)"
        tests:
          - not_null
      - name: AdCost
        description: "Cost of the advertisement associated with the interaction"
        tests:
          - not_null
      - name: IsNewCustomer
        description: "Flag indicating if the customer is new (TRUE/FALSE)"
        tests:
          - not_null
      - name: Revenue
        description: "Revenue generated from the interaction"
        tests:
          - not_null
      - name: SessionID
        description: "Unique ID for the user session"
        tests:
          - not_null

  - name: model_stg_campaign_master
    description: "Staging model for campaign master data"
    tags: staging
    columns:
      - name: CampaignID
        description: "Unique ID for the campaign"
        tests:
          - not_null
          - unique
      - name: CampaignName
        description: "The name of the campaign"
        tests:
          - not_null
      - name: Type
        description: "The type of the campaign"
        tests:
          - not_null
      - name: Objective
        description: "The objective of the campaign (e.g., awareness, conversion)"
        tests:
          - not_null
      - name: Channel
        description: "The marketing channel for the campaign (e.g., Facebook, Google)"
        tests:
          - not_null
      - name: Budget
        description: "The budget allocated for the campaign"
        tests:
          - not_null
      - name: CostModel
        description: "The cost model used for the campaign (e.g., CPM, CPC)"
        tests:
          - not_null
      - name: TargetingStrategy
        description: "The targeting strategy used in the campaign (e.g., demographic, geographic)"
        tests:
          - not_null
      - name: StartDate
        description: "The start date of the campaign"
        tests:
          - not_null
      - name: EndDate
        description: "The end date of the campaign"
        tests:
          - not_null
      - name: IsActive
        description: "Flag indicating if the campaign is currently active (TRUE/FALSE)"
        tests:
          - not_null

  - name: model_stg_customers_master
    description: "Staging model for customer master data"
    tags: staging
    columns:
      - name: CustomerID
        description: "Unique ID for the customer"
        tests:
          - not_null
          - unique
      - name: CustomerSegment
        description: "Segment the customer belongs to"
        tests:
          - not_null
      - name: Gender
        description: "Customer's gender"
        tests:
          - not_null
      - name: BirthYear
        description: "Customer's birth year"
        tests:
          - not_null
      - name: ReferralSource
        description: "Source of customer referral"
        tests:
          - not_null
      - name: PreferredDevice
        description: "Customer's preferred device"
        tests:
          - not_null
      - name: Signup
        description: "Date when customer signed up"
        tests:
          - not_null
      - name: Status
        description: "Customer's current status"
        tests:
          - not_null

  - name: model_stg_order_transactions
    description: "Staging model for order transaction data"
    tags: staging
    columns:
      - name: OrderID
        description: "Unique ID for the order"
        tests:
          - not_null
          - unique
      - name: CustomerID
        description: "ID of the customer who placed the order"
        tests:
          - not_null
      - name: RestaurantID
        description: "ID of the restaurant fulfilling the order"
        tests:
          - not_null
      - name: DriverID
        description: "ID of the driver delivering the order"
        tests:
          - not_null
      - name: OrderDatetime
        description: "Timestamp when the order was placed"
        tests:
          - not_null
      - name: PickupDatetime
        description: "Timestamp when the order was picked up"
        tests:
          - not_null
      - name: DeliveryDatetime
        description: "Timestamp when the order was delivered"
        tests:
          - not_null
      - name: OrderStatus
        description: "Current status of the order"
        tests:
          - not_null
      - name: DeliveryZone
        description: "Zone where the order was delivered"
        tests:
          - not_null
      - name: TotalAmount
        description: "Total amount for the order"
        tests:
          - not_null
      - name: PaymentMethod
        description: "Method used for payment"
        tests:
          - not_null
      - name: IsLateDelivery
        description: "Flag indicating if delivery was late (TRUE/FALSE)"
        tests:
          - not_null
      - name: DeliveryDistanceKM
        description: "Distance for delivery in kilometers"
        tests:
          - not_null


  - name: model_stg_campaign_interactions
    description: "Staging model for campaign interaction data"
    tags: staging
    columns:
      - name: InteractionID
        description: "Unique ID for the interaction"
        tests:
          - not_null
          - unique
      - name: CampaignID
        description: "Foreign Key referencing the campaign"
        tests:
          - not_null
      - name: OrderID
        description: "ID of the order linked to the interaction"
      - name: CustomerID
        description: "Foreign Key referencing the customer"
        tests:
          - not_null
      - name: InteractionDatetime
        description: "Timestamp of the interaction"
        tests:
          - not_null
      - name: EventType
        description: "Type of interaction event (e.g., click, impression)"
        tests:
          - not_null
      - name: Platform
        description: "Platform where the interaction took place (e.g., Google, Facebook)"
        tests:
          - not_null
      - name: DeviceType
        description: "Type of device used during the interaction (e.g., iOS, Android)"
        tests:
          - not_null
      - name: AdCost
        description: "Cost of the advertisement associated with the interaction"
        tests:
          - not_null
      - name: IsNewCustomer
        description: "Flag indicating if the customer is new (TRUE/FALSE)"
        tests:
          - not_null
      - name: Revenue
        description: "Revenue generated from the interaction"
        tests:
          - not_null
      - name: SessionID
        description: "Unique ID for the user session"
        tests:
          - not_null
